# playbook.yml
---
- name: Configure EC2 instances
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Python3 and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python packages
      pip:
        name:
          - psutil
          - prometheus_client
        state: present

    - name: Copy monitoring script
      copy:
        src: ../python/monitor.py
        dest: /opt/monitor.py
        mode: '0755'

    - name: Set up systemd service for monitoring
      template:
        src: monitor.service.j2
        dest: /etc/systemd/system/monitor.service
      notify:
        - Restart monitor service

  handlers:
    - name: Restart monitor service
      systemd:
        name: monitor
        state: restarted
        daemon_reload: yes

